apiVersion: v1
kind: Namespace
metadata:
  name: chars-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chars-pod
  namespace: chars-system
spec:
  selector:
    matchLabels:
      app: chars
  template:
    metadata:
      labels:
        app: chars
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: chars-api
        image: chars-api-image
        ports:
        - name: chars-api
          containerPort: 3000
        - name: chars-api-debug
          containerPort: 4000
        readinessProbe:
          httpGet:
            path: /debug/readiness
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 360
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /debug/liveness
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 120
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        env:
        - name: KUBERNETES_PODNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_NAMESPACE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace          
---
apiVersion: v1
kind: Service
metadata:
  name: chars-service
  namespace: chars-system
spec:
  type: ClusterIP
  selector:
    app: chars
  ports:
  - name: chars-api
    port: 3000
    targetPort: chars-api
  - name: chars-api-debug
    port: 4000
    targetPort: chars-api-debug
  