apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/chars-pod/
patchesStrategicMerge:
- ./kind-chars-patch.yaml
images:
- name: chars-api-image
  newName: chars-api
  newTag: "1.0"
